### ISSUE TITLE
[BUG]Containers Break Encumbrance System

### ISSUE THREAD

**Issue by justinthejaguar** [eegag/slot-based-encumbrance#5]
1. Create a container
2. Equip container
3. Delete container.

This will result in -1 encumbrance that I can't seem to undo.

**Comment by eegag** [comment]
I haven't been able to reproduce your defect yet. I tried with an empty container and a container with items, and after equipping and then deleting the container, the slot totals looked correct.

![image](https://user-images.githubusercontent.com/111909085/215769122-0049045a-8fcb-4cff-9991-66e5a0ed871b.png)

Container Man with no containers

![image](https://user-images.githubusercontent.com/111909085/215769274-ad5de3c5-f5f5-41ad-888f-e3689258738b.png)

Create new container, slots increase from 7 to 8 because an unused container takes up a slot.

![image](https://user-images.githubusercontent.com/111909085/215769692-a6117c5d-1cbb-4b54-be1b-e70d5c06f30b.png)

Equip container (moves from packed to carried), -1 slot total

![image](https://user-images.githubusercontent.com/111909085/215770006-d80eebea-e040-4752-b116-1bb47ea6f04d.png)

Delete container (throw it on the ground), slot total remains the same. Total = 7, as it was before I added the container.

What settings are you using? Could you paste your SBE settings screen?

**Comment by justinthejaguar** [comment]
I will try this again when I get home. I believe I might have been using STR as encumbrance.

**Comment by eegag** [comment]
Closed. Let me know the details if it happens again.
